insert into TBLMONTHLYINPUT ([BranchCode]
      ,[SalMonth]
      ,[SalYear]
      ,[EmployeeCode]
      ,[E_Basic]
      ,[E_SP]
      ,[E_FDA]
      ,[E_01]
      ,[E_02]
      ,[E_03]
      ,[E_04]
      ,[E_05]
      ,[E_06]
      ,[E_07]
      ,[E_08]
      ,[E_09]
      ,[E_10]
      ,[E_11]
      ,[E_12]
      ,[E_13]
      ,[E_14]
      ,[E_15]
      ,[E_16]
      ,[E_17]
      ,[E_18]
      ,[E_19]
      ,[E_20]
      ,[E_21]
      ,[E_22]
      ,[E_23]
      ,[E_24]
      ,[E_25]
      ,[E_26]
      ,[E_27]
      ,[E_28]
      ,[E_29]
      ,[E_30]
      ,[D_PF]
      ,[D_VPF]
      ,[D_01]
      ,[D_02]
      ,[D_03]
      ,[D_04]
      ,[D_05]
      ,[D_06]
      ,[D_07]
      ,[D_08]
      ,[D_09]
      ,[D_10]
      ,[D_11]
      ,[D_12]
      ,[D_13]
      ,[D_14]
      ,[D_15]
      ,[D_16]
      ,[D_17]
      ,[D_18]
      ,[D_19]
      ,[D_20]
      ,[D_21]
      ,[D_22]
      ,[D_23]
      ,[D_24]
      ,[D_25]
      ,[D_26]
      ,[D_27]
      ,[D_28]
      ,[D_29]
      ,[D_30]
      ,[C_TotEarn]
      ,[C_TotDedu]
      ,[C_NetSal]
      ,[C_Pension]
      ,[C_GrossSalary]
      ,[SalaryLock]
      ,[LWP]
      ,[OTHrs]
      ,[AOTHrs]
      ,[DeductPFLoan]
      ,[DeductNB]
      ,[DeductTCS]
      ,[DeductHouseLoan]
      ,[DeductFestivalLoan]
      ,[DeductCarLoan]
      ,[DeductScooterLoan]
      ,[DeductSundryAdv]
      ,[E_31]
      ,[E_32],CreatedBy,CreatedOn)
SELECT  [BranchCode]
      ,[SalMonth]
      ,[SalYear]
      ,[EmployeeCode]
      ,[E_Basic]
      ,[E_SP]
      ,[E_FDA]
      ,[E_01]
      ,[E_02]
      ,[E_03]
      ,[E_04]
      ,[E_05]
      ,[E_06]
      ,[E_07]
      ,[E_08]
      ,[E_09]
      ,[E_10]
      ,[E_11]
      ,[E_12]
      ,[E_13]
      ,[E_14]
      ,[E_15]
      ,[E_16]
      ,[E_17]
      ,[E_18]
      ,[E_19]
      ,[E_20]
      ,[E_21]
      ,[E_22]
      ,[E_23]
      ,[E_24]
      ,[E_25]
      ,[E_26]
      ,[E_27]
      ,[E_28]
      ,[E_29]
      ,[E_30]
      ,[D_PF]
      ,[D_VPF]
      ,[D_01]
      ,[D_02]
      ,[D_03]
      ,[D_04]
      ,[D_05]
      ,[D_06]
      ,[D_07]
      ,[D_08]
      ,[D_09]
      ,[D_10]
      ,[D_11]
      ,[D_12]
      ,[D_13]
      ,[D_14]
      ,[D_15]
      ,[D_16]
      ,[D_17]
      ,[D_18]
      ,[D_19]
      ,[D_20]
      ,[D_21]
      ,[D_22]
      ,[D_23]
      ,[D_24]
      ,[D_25]
      ,[D_26]
      ,[D_27]
      ,[D_28]
      ,[D_29]
      ,[D_30]
      ,[C_TotEarn]
      ,[C_TotDedu]
      ,[C_NetSal]
      ,[C_Pension]
      ,[C_GrossSalary]
      ,[SalaryLock]
      ,[LWP]
      ,[OTHrs]
      ,[AOTHrs]
      ,[DeductPFLoan]
      ,[DeductNB]
      ,[DeductTCS]
      ,[DeductHouseLoan]
      ,[DeductFestivalLoan]
      ,[DeductCarLoan]
      ,[DeductScooterLoan]
      ,[DeductSundryAdv]
      ,[E_31]
      ,[E_32] ,1 , getdate() 
  FROM [MicroPayB4].[dbo].[TBLMONTHLYINPUT]  where SalYear =2020 and SalMonth =3 

		  UPDATE A    
SET EmployeeId = RA.EmployeeId
FROM TBLMONTHLYINPUT A
INNER JOIN tblMstEmployee RA
ON A.EmployeeCode = RA.EmployeeCode

UPDATE A    
SET BranchID = RA.BranchID
FROM TBLMONTHLYINPUT A
INNER JOIN Branch RA
ON substring(A.BranchCode, patindex('%[^0]%',A.BranchCode), 10) = RA.BranchCode

----==========  Branch Id mapping --- Date - 05-May-2020
UPDATE A    
SET BranchID = RA.BranchID
FROM tblLoanTrans A inner join MicroPayB4.dbo.BranchMapping BM
on A.BranchCode = BM.branchcode
INNER JOIN Branch RA
ON  case when BM.NewBranchCode = '' or NewBranchCode is null then 
case when len(BM.BranchCode) = 1 then '0' + BM.BranchCode else BM.BranchCode end
else 
case when len(NewBranchCode) = 1 then '0' + NewBranchCode else NewBranchCode end  
end = 
case when len(RA.BranchCode) = 1 then '0' + RA.BranchCode  else RA.BranchCode end



update tblmonthlyinput set branchid = e.branchid , BranchCode = b.branchcode
from tblMstEmployee e inner join tblmonthlyinput m  
on e.EmployeeId  = m.EmployeeId
inner join branch b on e.BranchID = b.BranchID