//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APARSkillSetFormDetail
    {
        public int FormDetailID { get; set; }
        public int APARHdrID { get; set; }
        public int PartID { get; set; }
        public int SkillTypeID { get; set; }
        public int SkillID { get; set; }
        public Nullable<decimal> Grading { get; set; }
        public bool IsDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string Remark { get; set; }
        public int SkillSetID { get; set; }
        public Nullable<decimal> ReportingGrading { get; set; }
        public string ReportingRemarks { get; set; }
    
        public virtual APARSkillSet APARSkillSet { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
