//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArrearDetail
    {
        public string BranchCode { get; set; }
        public string SalMonth { get; set; }
        public short SalYear { get; set; }
        public int SeqNo { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<decimal> E_Basic { get; set; }
        public Nullable<decimal> E_SP { get; set; }
        public Nullable<decimal> E_FDA { get; set; }
        public Nullable<decimal> E_01 { get; set; }
        public Nullable<decimal> E_02 { get; set; }
        public Nullable<decimal> E_03 { get; set; }
        public Nullable<decimal> E_04 { get; set; }
        public Nullable<decimal> E_05 { get; set; }
        public Nullable<decimal> E_06 { get; set; }
        public Nullable<decimal> E_07 { get; set; }
        public Nullable<decimal> E_08 { get; set; }
        public Nullable<decimal> E_09 { get; set; }
        public Nullable<decimal> E_10 { get; set; }
        public Nullable<decimal> E_11 { get; set; }
        public Nullable<decimal> E_12 { get; set; }
        public Nullable<decimal> E_13 { get; set; }
        public Nullable<decimal> E_14 { get; set; }
        public Nullable<decimal> E_15 { get; set; }
        public Nullable<decimal> E_16 { get; set; }
        public Nullable<decimal> E_17 { get; set; }
        public Nullable<decimal> E_18 { get; set; }
        public Nullable<decimal> E_19 { get; set; }
        public Nullable<decimal> E_20 { get; set; }
        public Nullable<decimal> E_21 { get; set; }
        public Nullable<decimal> E_22 { get; set; }
        public Nullable<decimal> E_23 { get; set; }
        public Nullable<decimal> E_24 { get; set; }
        public Nullable<decimal> E_25 { get; set; }
        public Nullable<decimal> E_26 { get; set; }
        public Nullable<decimal> E_27 { get; set; }
        public Nullable<decimal> E_28 { get; set; }
        public Nullable<decimal> E_29 { get; set; }
        public Nullable<decimal> E_30 { get; set; }
        public Nullable<decimal> D_PF { get; set; }
        public Nullable<decimal> D_VPF { get; set; }
        public Nullable<decimal> D_01 { get; set; }
        public Nullable<decimal> D_02 { get; set; }
        public Nullable<decimal> D_03 { get; set; }
        public Nullable<decimal> D_04 { get; set; }
        public Nullable<decimal> D_05 { get; set; }
        public Nullable<decimal> D_06 { get; set; }
        public Nullable<decimal> D_07 { get; set; }
        public Nullable<decimal> D_08 { get; set; }
        public Nullable<decimal> D_09 { get; set; }
        public Nullable<decimal> D_10 { get; set; }
        public Nullable<decimal> D_11 { get; set; }
        public Nullable<decimal> D_12 { get; set; }
        public Nullable<decimal> D_13 { get; set; }
        public Nullable<decimal> D_14 { get; set; }
        public Nullable<decimal> D_15 { get; set; }
        public Nullable<decimal> D_16 { get; set; }
        public Nullable<decimal> D_17 { get; set; }
        public Nullable<decimal> D_18 { get; set; }
        public Nullable<decimal> D_19 { get; set; }
        public Nullable<decimal> D_20 { get; set; }
        public Nullable<decimal> D_21 { get; set; }
        public Nullable<decimal> D_22 { get; set; }
        public Nullable<decimal> D_23 { get; set; }
        public Nullable<decimal> D_24 { get; set; }
        public Nullable<decimal> D_25 { get; set; }
        public Nullable<decimal> D_26 { get; set; }
        public Nullable<decimal> D_27 { get; set; }
        public Nullable<decimal> D_28 { get; set; }
        public Nullable<decimal> D_29 { get; set; }
        public Nullable<decimal> D_30 { get; set; }
        public string DateOfGenerateArrear { get; set; }
        public string ArrearType { get; set; }
        public Nullable<double> E_BASIC_INC { get; set; }
        public Nullable<double> RateADAA { get; set; }
        public Nullable<double> RateHRAA { get; set; }
        public Nullable<double> RatePFA { get; set; }
        public Nullable<decimal> sum_e_01 { get; set; }
        public string TOTDAYS_LWPDAYS { get; set; }
        public Nullable<int> NOOFMONTH { get; set; }
        public Nullable<decimal> OLD_DA { get; set; }
        public Nullable<decimal> Sequence { get; set; }
        public Nullable<System.DateTime> DateOfGenerate { get; set; }
        public Nullable<int> PeriodFrom { get; set; }
        public Nullable<int> PeriodTo { get; set; }
        public string Formula { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
