
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CandidateEducationSummary
{

    public int Counter { get; set; }

    public int RegistrationID { get; set; }

    public Nullable<int> FromMonth { get; set; }

    public Nullable<int> FromYear { get; set; }

    public Nullable<int> ToMonth { get; set; }

    public Nullable<int> ToYear { get; set; }

    public string DegreeDiploma { get; set; }

    public string University_Institute { get; set; }

    public string Specialization_Subjects { get; set; }

    public bool Percentage_GradeSystem { get; set; }

    public Nullable<decimal> Percentage { get; set; }

    public string Grade { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public int JSelectedQualificationID { get; set; }



    public virtual CandidateRegistration CandidateRegistration { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
