//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmationFormHdr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConfirmationFormHdr()
        {
            this.ConfirmationClarifications = new HashSet<ConfirmationClarification>();
            this.ConfirmationFormAHeaders = new HashSet<ConfirmationFormAHeader>();
            this.ConfirmationFormBHeaders = new HashSet<ConfirmationFormBHeader>();
            this.ConfirmationStatus = new HashSet<ConfirmationStatu>();
            this.ConfirmationStatus1 = new HashSet<ConfirmationStatu>();
            this.ConfirmationStatus2 = new HashSet<ConfirmationStatu>();
        }
    
        public int FormHdrID { get; set; }
        public int FormTypeID { get; set; }
        public int ProcessID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public int EmployeeID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmationClarification> ConfirmationClarifications { get; set; }
        public virtual ConfirmationForm ConfirmationForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmationFormAHeader> ConfirmationFormAHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmationFormBHeader> ConfirmationFormBHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmationStatu> ConfirmationStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmationStatu> ConfirmationStatus1 { get; set; }
        public virtual Process Process { get; set; }
        public virtual tblMstEmployee tblMstEmployee { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmationStatu> ConfirmationStatus2 { get; set; }
    }
}
