//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConveyanceBillHdrDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ConveyanceBillHdrDetail()
        {
            this.ConveyanceBillDescriptions = new HashSet<ConveyanceBillDescription>();
            this.ConveyanceBillHdrs = new HashSet<ConveyanceBillHdr>();
        }
    
        public int ConveyanceBillDetailID { get; set; }
        public string ReportingYear { get; set; }
        public int EmployeeID { get; set; }
        public int DesignationID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string Section { get; set; }
        public Nullable<decimal> TotalAmountClaimed { get; set; }
        public bool VehicleProvided { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int FormState { get; set; }
        public bool IsReportingRejected { get; set; }
        public bool IsReviewingRejected { get; set; }
        public string ReportingRemarks { get; set; }
        public string ReviewingRemarks { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConveyanceBillDescription> ConveyanceBillDescriptions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConveyanceBillHdr> ConveyanceBillHdrs { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual tblMstEmployee tblMstEmployee { get; set; }
        public virtual User User { get; set; }
    }
}
