
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class DeductionSubSectionDescription
{

    public int SectionID { get; set; }

    public int SubSectionID { get; set; }

    public int DescriptionID { get; set; }

    public string Description { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }



    public virtual DeductionSection DeductionSection { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual User User2 { get; set; }

}

}
