//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailConfiguration
    {
        public int EmailConfigurationID { get; set; }
        public string ToEmail { get; set; }
        public string Bcc { get; set; }
        public string CcEmail { get; set; }
        public string Password { get; set; }
        public string Server { get; set; }
        public int Port { get; set; }
        public string Signature { get; set; }
        public bool SSLStatus { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> MaintenanceDateTime { get; set; }
        public bool IsMaintenance { get; set; }
        public string UserName { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
