
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EmpAttendanceHdr
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EmpAttendanceHdr()
    {

        this.EmpAttendanceDetails = new HashSet<EmpAttendanceDetail>();

    }


    public int EmpAttendanceID { get; set; }

    public int EmployeeId { get; set; }

    public System.DateTime ProxydateIn { get; set; }

    public string InTime { get; set; }

    public string OutTime { get; set; }

    public string Remarks { get; set; }

    public int MarkedBy { get; set; }

    public int Attendancestatus { get; set; }

    public int TypeID { get; set; }

    public string Mode { get; set; }

    public string Old_Intime { get; set; }

    public string Old_outtime { get; set; }

    public System.DateTime ProxyOutDate { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<int> ReportingOfficer { get; set; }

    public Nullable<int> ReviewerTo { get; set; }

    public string ReportingToRemark { get; set; }

    public string ReviewerToRemark { get; set; }

    public string AcceptanceAuthRemark { get; set; }

    public Nullable<int> LocationID { get; set; }

    public string OtherLocation { get; set; }

    public Nullable<int> DesignationID { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public Nullable<System.DateTime> ReleavingDate { get; set; }

    public Nullable<System.DateTime> JoiningDate { get; set; }

    public Nullable<System.DateTime> JoinBackDate { get; set; }

    public Nullable<System.DateTime> ReleavDateFromLoc { get; set; }



    public virtual AttendanceType AttendanceType { get; set; }

    public virtual Branch Branch { get; set; }

    public virtual Designation Designation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpAttendanceDetail> EmpAttendanceDetails { get; set; }

    public virtual tblMstEmployee tblMstEmployee { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
