
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EmpDeductionUnderChapterVI_A
{

    public int EmpDeductionID { get; set; }

    public int EmpFormID { get; set; }

    public int EmployeeID { get; set; }

    public string FYear { get; set; }

    public int SectionID { get; set; }

    public Nullable<int> SubSectionID { get; set; }

    public Nullable<int> SubSectionDescriptionID { get; set; }

    public Nullable<decimal> Amount { get; set; }

    public bool IsDeleted { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }



    public virtual EmployeeForm12BB EmployeeForm12BB { get; set; }

    public virtual tblMstEmployee tblMstEmployee { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual DeductionSection DeductionSection { get; set; }

}

}
