//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProvidentFundOrganisation
    {
        public int ID { get; set; }
        public int EmpPFID { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> Employee_PF_Scheme_1952 { get; set; }
        public Nullable<int> Employee_Pension_Scheme_1995 { get; set; }
        public string Universal_Acc_No { get; set; }
        public Nullable<int> Previous_PF_Acc_No { get; set; }
        public Nullable<System.DateTime> Dateof_Exit_Previos_Employment { get; set; }
        public string Scheme_Certificate_No { get; set; }
        public string Pension_payment_Order_No { get; set; }
        public Nullable<int> International_Worker { get; set; }
        public string State_Country_Origin { get; set; }
        public string Passport_No { get; set; }
        public Nullable<System.DateTime> Validity_Passport_from { get; set; }
        public Nullable<System.DateTime> Validity_Passport_to { get; set; }
        public string BankAcNo { get; set; }
        public string IFSCCode { get; set; }
        public string AadhaarNo { get; set; }
        public string Permanent_AcNo { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public string PassportNoFilePath { get; set; }
        public string BankAcFilePath { get; set; }
        public string AadhaarCardFilePath { get; set; }
        public string PanCardFilePath { get; set; }
        public Nullable<int> PFNo { get; set; }
        public Nullable<System.DateTime> CurrentDate { get; set; }
        public bool EmployeeDeclaration { get; set; }
    
        public virtual tblMstEmployee tblMstEmployee { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual EmpPFOrgHDR EmpPFOrgHDR { get; set; }
    }
}
