
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeType
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public EmployeeType()
    {

        this.LeaveCreditRules = new HashSet<LeaveCreditRule>();

        this.LeaveCategories = new HashSet<LeaveCategory>();

        this.salaryheadshistories = new HashSet<salaryheadshistory>();

        this.SalaryHeads = new HashSet<SalaryHead>();

        this.tblMstEmployees = new HashSet<tblMstEmployee>();

        this.tblMstEmployees1 = new HashSet<tblMstEmployee>();

        this.tblFinalMonthlySalaries = new HashSet<tblFinalMonthlySalary>();

        this.BranchSalaryHeadRules = new HashSet<BranchSalaryHeadRule>();

        this.PayrollApprovalRequests = new HashSet<PayrollApprovalRequest>();

        this.MaxEmpCodeTypeWises = new HashSet<MaxEmpCodeTypeWise>();

        this.MailFailedLog = new HashSet<MailFailedLog>();

    }


    public int EmployeeTypeID { get; set; }

    public string EmployeeTypeCode { get; set; }

    public string EmployeeTypeName { get; set; }

    public bool IsDeleted { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }



    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveCreditRule> LeaveCreditRules { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveCategory> LeaveCategories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<salaryheadshistory> salaryheadshistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SalaryHead> SalaryHeads { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstEmployee> tblMstEmployees { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstEmployee> tblMstEmployees1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFinalMonthlySalary> tblFinalMonthlySalaries { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BranchSalaryHeadRule> BranchSalaryHeadRules { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PayrollApprovalRequest> PayrollApprovalRequests { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MaxEmpCodeTypeWise> MaxEmpCodeTypeWises { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MailFailedLog> MailFailedLog { get; set; }

}

}
