
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class EmployeeForm12BBDocument
{

    public int Form12BBDocumentID { get; set; }

    public int EmpFormID { get; set; }

    public string NatureOfClaim { get; set; }

    public string FileName { get; set; }

    public string FileDescription { get; set; }

    public Nullable<int> SectionID { get; set; }

    public Nullable<int> SubSectionID { get; set; }

    public Nullable<int> SubSectionDescriptionID { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }



    public virtual EmployeeForm12BB EmployeeForm12BB { get; set; }

    public virtual User User { get; set; }

}

}
