//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDependent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeDependent()
        {
            this.ChildrenEducationDetails = new HashSet<ChildrenEducationDetail>();
            this.InsuranceDependents = new HashSet<InsuranceDependent>();
        }
    
        public int EmpDependentID { get; set; }
        public string EmpCode { get; set; }
        public int DependentCode { get; set; }
        public string DependentName { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> RelationID { get; set; }
        public bool Handicapped { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int EmployeeId { get; set; }
        public bool PFNominee { get; set; }
        public Nullable<decimal> PFDistribution { get; set; }
        public bool EPSNominee { get; set; }
        public string Address { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Relation Relation { get; set; }
        public virtual tblMstEmployee tblMstEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChildrenEducationDetail> ChildrenEducationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InsuranceDependent> InsuranceDependents { get; set; }
    }
}
