//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeForm12BB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmployeeForm12BB()
        {
            this.EmpDeductionUnderChapterVI_A = new HashSet<EmpDeductionUnderChapterVI_A>();
            this.EmployeeForm12BBDocument = new HashSet<EmployeeForm12BBDocument>();
        }
    
        public int EmpFormID { get; set; }
        public string FYear { get; set; }
        public int EmployeeID { get; set; }
        public string LandLordName { get; set; }
        public string LandLordAddress { get; set; }
        public string LandLordPANNo { get; set; }
        public Nullable<decimal> RendPaidToLandLord { get; set; }
        public Nullable<decimal> InterestPaidToLender { get; set; }
        public string LenderName { get; set; }
        public string LenderAddress { get; set; }
        public string Fin_Institute_PANNo { get; set; }
        public string Employer_PANNo { get; set; }
        public string Other_PANNo { get; set; }
        public byte FormState { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> SubmittedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpDeductionUnderChapterVI_A> EmpDeductionUnderChapterVI_A { get; set; }
        public virtual tblMstEmployee tblMstEmployee { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeForm12BBDocument> EmployeeForm12BBDocument { get; set; }
    }
}
