
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ExamCenterDetail
{

    public int ExamCenterID { get; set; }

    public int RequirementID { get; set; }

    public int LocTypeID { get; set; }

    public Nullable<int> SelectedLocID { get; set; }

    public string ExamCentreAddress { get; set; }

    public System.TimeSpan ReportingTime { get; set; }

    public System.TimeSpan EntryCloseTime { get; set; }

    public System.TimeSpan ExamTiming { get; set; }



    public virtual Branch Branch { get; set; }

    public virtual Requirement Requirement { get; set; }

}

}
