//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileManagement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FileManagement()
        {
            this.FileTrackingDocuments = new HashSet<FileTrackingDocument>();
        }
    
        public int FileID { get; set; }
        public string DiaryNo { get; set; }
        public string OtherDiaryNo { get; set; }
        public int DepartmentID { get; set; }
        public string FileSubject { get; set; }
        public string FileName { get; set; }
        public Nullable<int> FileLastStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int FileWorkFlowID { get; set; }
        public int FileTypeID { get; set; }
        public System.DateTime FilePutup { get; set; }
        public byte StatusID { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual FileTrackingType FileTrackingType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FileTrackingDocument> FileTrackingDocuments { get; set; }
        public virtual FileWorkflow FileWorkflow { get; set; }
    }
}
