
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FormGroupFHdr
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public FormGroupFHdr()
    {

        this.FormGroupFDetail1 = new HashSet<FormGroupFDetail1>();

        this.FormGroupFDetail2 = new HashSet<FormGroupFDetail2>();

    }


    public string ReportingYr { get; set; }

    public int FormGroupID { get; set; }

    public int FormID { get; set; }

    public int EmployeeID { get; set; }

    public Nullable<System.DateTime> WorkedPeriodUnderROFrom { get; set; }

    public Nullable<System.DateTime> WorkedPeriodUnderROTo { get; set; }

    public string PART2_1 { get; set; }

    public string PART2_3A { get; set; }

    public string PART2_3B { get; set; }

    public string PART2_4 { get; set; }

    public Nullable<byte> PART4_1_Grade { get; set; }

    public string PART4_1_Remark { get; set; }

    public Nullable<byte> PART4_2_Grade { get; set; }

    public string PART4_2_Remark { get; set; }

    public Nullable<byte> PART4_3_Grade { get; set; }

    public string PART4_3_Remark { get; set; }

    public Nullable<byte> PART4_4_Grade { get; set; }

    public string PART4_4_Remark { get; set; }

    public Nullable<byte> PART4_5_Grade { get; set; }

    public string PART4_5_Remark { get; set; }

    public Nullable<decimal> PART4_6_Weightage { get; set; }

    public string PART4_6_Remark { get; set; }

    public string PART5_1 { get; set; }

    public bool PART5_2 { get; set; }

    public string PART5_3 { get; set; }

    public string PART5_4 { get; set; }

    public string PART5_5 { get; set; }

    public Nullable<decimal> PART5_6_Weightage { get; set; }

    public string PART5_6_Remark { get; set; }

    public string Remarks { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public int FormState { get; set; }

    public int DesignationID { get; set; }

    public int DepartmentID { get; set; }



    public virtual Department Department { get; set; }

    public virtual Designation Designation { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupFDetail1> FormGroupFDetail1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupFDetail2> FormGroupFDetail2 { get; set; }

    public virtual tblMstEmployee tblMstEmployee { get; set; }

    public virtual AppraisalForm AppraisalForm { get; set; }

}

}
