//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormGroupGHdr
    {
        public string ReportingYr { get; set; }
        public int FormGroupID { get; set; }
        public int FormID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<System.DateTime> WorkedPeriodUnderROFrom { get; set; }
        public Nullable<System.DateTime> WorkedPeriodUnderROTo { get; set; }
        public byte JobPerformance_A { get; set; }
        public byte AdherenceToInstructions_A { get; set; }
        public byte AdherenceToInstructions_B { get; set; }
        public byte Safety_A { get; set; }
        public byte Safety_B { get; set; }
        public byte Safety_C_1 { get; set; }
        public byte Safety_C_2 { get; set; }
        public byte MAINTENANCE_A { get; set; }
        public byte MAINTENANCE_B { get; set; }
        public byte DEPENDABILITY_A { get; set; }
        public byte DISCIPLINE_GENERAL_BEHAVIOUR_A { get; set; }
        public byte DISCIPLINE_GENERAL_BEHAVIOUR_B_1 { get; set; }
        public byte DISCIPLINE_GENERAL_BEHAVIOUR_B_2 { get; set; }
        public byte REGULARITY_PUNCTUALITY_A { get; set; }
        public byte REGULARITY_PUNCTUALITY_B { get; set; }
        public byte TECHNICAL_KNOWLEDGE_A { get; set; }
        public byte TECHNICAL_KNOWLEDGE_B { get; set; }
        public byte RECORD_KEEPING_A { get; set; }
        public byte INTEGRITY { get; set; }
        public Nullable<byte> total { get; set; }
        public string ReportingOfficeComment { get; set; }
        public string ReviewingOfficerComment { get; set; }
        public string AcceptanceAuthorityComment { get; set; }
        public bool AcceleratedPromotion { get; set; }
        public bool PromotionInDueCourse { get; set; }
        public int FormState { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string EmpPotentialDevelopment { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual tblMstEmployee tblMstEmployee { get; set; }
        public virtual AppraisalForm AppraisalForm { get; set; }
    }
}
