//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormGroupDHdr
    {
        public string ReportingYr { get; set; }
        public int FormGroupID { get; set; }
        public int FormID { get; set; }
        public int EmployeeID { get; set; }
        public int DesignationID { get; set; }
        public int DepartmentID { get; set; }
        public Nullable<System.DateTime> WorkedPeriodUnderROFrom { get; set; }
        public Nullable<System.DateTime> WorkedPeriodUnderROTo { get; set; }
        public string Part2_1 { get; set; }
        public string Part2_2 { get; set; }
        public string Part2_3 { get; set; }
        public string Part2_4 { get; set; }
        public string Part3_1 { get; set; }
        public Nullable<decimal> Part3_2_A_1 { get; set; }
        public Nullable<decimal> Part3_2_A_2 { get; set; }
        public Nullable<decimal> Part3_2_A_3 { get; set; }
        public Nullable<decimal> Part3_2_A_4 { get; set; }
        public Nullable<decimal> Part3_2_B_1 { get; set; }
        public Nullable<decimal> Part3_2_B_2 { get; set; }
        public Nullable<decimal> Part3_2_B_3 { get; set; }
        public Nullable<decimal> Part3_2_B_4 { get; set; }
        public Nullable<decimal> Part3_2_B_5 { get; set; }
        public Nullable<decimal> Part3_2_B_6 { get; set; }
        public Nullable<decimal> Part3_2_B_7 { get; set; }
        public Nullable<decimal> Part3_2_B_8 { get; set; }
        public Nullable<decimal> Part3_2_C_1 { get; set; }
        public Nullable<decimal> Part3_2_C_2 { get; set; }
        public Nullable<decimal> Part3_2_C_3 { get; set; }
        public Nullable<decimal> Part3_2_C_4 { get; set; }
        public Nullable<decimal> Part3_2_C_5 { get; set; }
        public Nullable<decimal> Part3_2_C_6 { get; set; }
        public string Part4_1 { get; set; }
        public string Part4_2 { get; set; }
        public string Part4_3 { get; set; }
        public string Part4_4 { get; set; }
        public string Part4_5 { get; set; }
        public string Part5_1 { get; set; }
        public Nullable<bool> Part5_2 { get; set; }
        public string Part5_3 { get; set; }
        public string Part5_4 { get; set; }
        public string ReportingOfficerRemarks { get; set; }
        public string ReviewingOfficerRemarks { get; set; }
        public string AcceptanceAuthorityRemarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public int FormState { get; set; }
        public Nullable<byte> PART4_1_Grade { get; set; }
        public Nullable<byte> PART4_3_Grade { get; set; }
        public Nullable<byte> PART4_4_Grade { get; set; }
        public string PART4_6_Remark { get; set; }
        public Nullable<decimal> Part3_A_Overall_Grading { get; set; }
        public Nullable<decimal> Part3_B_Overall_Grading { get; set; }
        public Nullable<decimal> Part3_C_Overall_Grading { get; set; }
        public Nullable<decimal> PART4_6_Grade { get; set; }
        public Nullable<decimal> PART5_5_Grade { get; set; }
        public string PART5_5_Remark { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual FormGroupDHdr FormGroupDHdr1 { get; set; }
        public virtual FormGroupDHdr FormGroupDHdr2 { get; set; }
        public virtual User User { get; set; }
        public virtual AppraisalForm AppraisalForm { get; set; }
    }
}
