
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class InsufficientLoggingMonitoring
{

    public long Id { get; set; }

    public string UserName { get; set; }

    public string SessionId { get; set; }

    public string IP_address { get; set; }

    public System.DateTime DateTime { get; set; }

    public string Referrer { get; set; }

    public string ProcessId { get; set; }

    public string URL { get; set; }

    public string UserAgent { get; set; }

    public string Country { get; set; }

}

}
