
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class InventoryManagement
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public InventoryManagement()
    {

        this.AssetmanagementDetails = new HashSet<AssetmanagementDetail>();

    }


    public int IMID { get; set; }

    public int AssetTypeID { get; set; }

    public int ManufacturerID { get; set; }

    public string AssetName { get; set; }

    public string SerialNo { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<bool> Consumable { get; set; }

    public string Remarks { get; set; }

    public Nullable<int> StatusID { get; set; }

    public bool IsDeleted { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public string ManufacturingYr { get; set; }



    public virtual AssetType AssetType { get; set; }

    public virtual User User { get; set; }

    public virtual Manufacturer Manufacturer { get; set; }

    public virtual User User1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AssetmanagementDetail> AssetmanagementDetails { get; set; }

}

}
