//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequirementQualification
    {
        public int JQualifactionID { get; set; }
        public int RequirementID { get; set; }
        public Nullable<int> JQualificationTypeID { get; set; }
        public int SelectedQualificationID { get; set; }
    
        public virtual Requirement Requirement { get; set; }
    }
}
