//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRequirementLocation
    {
        public int JLocId { get; set; }
        public int RequirementId { get; set; }
        public int LocTypeId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> ZoneId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Requirement Requirement { get; set; }
    }
}
