
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LeaveCreditRule
{

    public int CreditRuleID { get; set; }

    public int LeaveCategoryID { get; set; }

    public int C_YearID { get; set; }

    public int FromMonth { get; set; }

    public int ToMonth { get; set; }

    public int Credit { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<bool> IsDOJDepenedent { get; set; }

    public Nullable<int> EmployeeTypeID { get; set; }



    public virtual CalendarYear CalendarYear { get; set; }

    public virtual EmployeeType EmployeeType { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual LeaveCategory LeaveCategory { get; set; }

}

}
