//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LeaveCategory()
        {
            this.EmployeeLeaves = new HashSet<EmployeeLeave>();
            this.tblMedicalLeaveUpdates = new HashSet<tblMedicalLeaveUpdate>();
            this.tblLeaveUpdates = new HashSet<tblLeaveUpdate>();
            this.LeaveCreditRules = new HashSet<LeaveCreditRule>();
            this.LeavePurposes = new HashSet<LeavePurpose>();
            this.LeaveRules = new HashSet<LeaveRule>();
        }
    
        public int LeaveCategoryID { get; set; }
        public string LeaveCode { get; set; }
        public string LeaveCategoryName { get; set; }
        public bool DeductFromSalary { get; set; }
        public bool CarryForward { get; set; }
        public int MaxCFUnit { get; set; }
        public int MaxLeave { get; set; }
        public string Remarks { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public Nullable<int> GenderID { get; set; }
        public Nullable<bool> IsSanwichSystem { get; set; }
        public Nullable<int> DependentOnLeaveBal { get; set; }
        public string leaveGuidelines { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public Nullable<int> ApprovalRequiredUpto { get; set; }
        public Nullable<int> MinLeave { get; set; }
        public Nullable<int> AllowLevelUpto { get; set; }
        public Nullable<int> fullpay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblMedicalLeaveUpdate> tblMedicalLeaveUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLeaveUpdate> tblLeaveUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveCreditRule> LeaveCreditRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeavePurpose> LeavePurposes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaveRule> LeaveRules { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
