
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LoanApplication
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LoanApplication()
    {

        this.LoanApplicationHistories = new HashSet<LoanApplicationHistory>();

    }


    public int ApplicationID { get; set; }

    public int EmployeeID { get; set; }

    public decimal LoanAmount { get; set; }

    public byte LoanReason { get; set; }

    public string Ceremony { get; set; }

    public Nullable<System.DateTime> CeremonyDate { get; set; }

    public string CeremonyPlace { get; set; }

    public string DeathPlace { get; set; }

    public byte StatusID { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<int> UpdateBy { get; set; }

    public Nullable<System.DateTime> UpdateOn { get; set; }



    public virtual tblMstEmployee tblMstEmployee { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LoanApplicationHistory> LoanApplicationHistories { get; set; }

}

}
