
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MaxEmpCodeTypeWise
{

    public int ID { get; set; }

    public int MaxEmployee { get; set; }

    public string Prifix { get; set; }

    public int EmployeeTypeID { get; set; }



    public virtual EmployeeType EmployeeType { get; set; }

}

}
