//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessWorkFlow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessWorkFlow()
        {
            this.APARReviewedSignedCopies = new HashSet<APARReviewedSignedCopy>();
        }
    
        public int WorkflowID { get; set; }
        public int ProcessID { get; set; }
        public Nullable<int> ReferenceID { get; set; }
        public Nullable<int> SenderID { get; set; }
        public Nullable<int> ReceiverID { get; set; }
        public Nullable<System.DateTime> Senddate { get; set; }
        public Nullable<System.DateTime> Readdate { get; set; }
        public Nullable<int> Readflag { get; set; }
        public string Scomments { get; set; }
        public Nullable<int> Forwarded_WorkflowID { get; set; }
        public string Purpose { get; set; }
        public Nullable<int> StatusID { get; set; }
        public int EmployeeID { get; set; }
        public Nullable<int> SenderDesignationID { get; set; }
        public Nullable<int> ReceiverDesignationID { get; set; }
        public Nullable<int> SenderDepartmentID { get; set; }
        public Nullable<int> ReceiverDepartmentID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> ReadBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APARReviewedSignedCopy> APARReviewedSignedCopies { get; set; }
    }
}
