
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Resignation
{

    public int ResignationId { get; set; }

    public int EmployeeId { get; set; }

    public System.DateTime ResignationDate { get; set; }

    public Nullable<int> NoticePeriod { get; set; }

    public Nullable<int> Reason { get; set; }

    public string OtherReason { get; set; }

    public Nullable<int> StatusId { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public string DocName { get; set; }



    public virtual tblMstEmployee tblMstEmployee { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
