
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sepration
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Sepration()
    {

        this.SeparationClearances = new HashSet<SeparationClearance>();

    }


    public int SeprationId { get; set; }

    public int EmployeeId { get; set; }

    public int SeprationType { get; set; }

    public System.DateTime DateOfAction { get; set; }

    public Nullable<int> NoticePeriod { get; set; }

    public Nullable<int> Reason { get; set; }

    public string DocumentName { get; set; }

    public string DocumentPath { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> StatusId { get; set; }

    public string CircularDocument { get; set; }

    public string FileNo { get; set; }

    public string ReferenceNo { get; set; }

    public Nullable<System.DateTime> ApprovedDate { get; set; }

    public string OtherReason { get; set; }

    public Nullable<System.DateTime> ClearanceDateUpto { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SeparationClearance> SeparationClearances { get; set; }

    public virtual tblMstEmployee tblMstEmployee { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
