//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSConfiguration
    {
        public int SMSConfigurationID { get; set; }
        public string ApiKey { get; set; }
        public string SMSUrl { get; set; }
        public string SenderID { get; set; }
        public string Channel { get; set; }
        public string DCS { get; set; }
        public string FlashSMS { get; set; }
        public string Route { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
