//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubordinatesTraining
    {
        public int SubTrnID { get; set; }
        public string ReportingYr { get; set; }
        public int EmployeeID { get; set; }
        public byte TrainingID { get; set; }
        public string Remark { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpatedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual tblMstEmployee tblMstEmployee { get; set; }
        public virtual User User1 { get; set; }
    }
}
