
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TblBonusAmt
{

    public int BonusAmtID { get; set; }

    public int BranchID { get; set; }

    public int EmployeeID { get; set; }

    public string Empcode { get; set; }

    public int EmployeeTypeID { get; set; }

    public Nullable<decimal> Qual_Amt_tot { get; set; }

    public Nullable<decimal> C4percent { get; set; }

    public Nullable<decimal> C8percent { get; set; }

    public Nullable<decimal> C8_33percent { get; set; }

    public Nullable<decimal> C12percent { get; set; }

    public Nullable<decimal> C20percent { get; set; }

    public Nullable<decimal> C11_67percent { get; set; }

    public Nullable<decimal> ActBonus_Amt { get; set; }

    public string Percentage_Given { get; set; }

    public Nullable<int> Year { get; set; }

    public Nullable<int> Month { get; set; }

    public Nullable<int> Days { get; set; }

    public bool IsDeleted { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }



    public virtual Branch Branch { get; set; }

    public virtual User User { get; set; }

    public virtual tblMstEmployee tblMstEmployee { get; set; }

    public virtual User User1 { get; set; }

}

}
