
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblBranchManagerDetail
{

    public int Id { get; set; }

    public int BranchCode { get; set; }

    public string EmployeeCode { get; set; }

    public System.DateTime DateFrom { get; set; }

    public Nullable<System.DateTime> DateTo { get; set; }

    public Nullable<bool> BranchOffice { get; set; }

    public Nullable<bool> OnLeave { get; set; }

    public Nullable<bool> OnTour { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<int> EmployeeID { get; set; }

    public Nullable<int> branchID { get; set; }

    public bool IsDeleted { get; set; }



    public virtual Branch Branch { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual tblMstEmployee tblMstEmployee { get; set; }

}

}
