
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblCCAMaster
{

    public decimal UpperLimit { get; set; }

    public Nullable<decimal> AmtCityGradeA1 { get; set; }

    public Nullable<decimal> AmtCityGradeA { get; set; }

    public Nullable<decimal> AmtCityGradeB1 { get; set; }

    public Nullable<decimal> AmtCityGradeB2 { get; set; }

    public Nullable<System.DateTime> CreatedOn { get; set; }

    public Nullable<int> CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public bool IsDeleted { get; set; }

    public Nullable<decimal> AmtCityGradeC { get; set; }



    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

}

}
