//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeQualificationdetail
    {
        public int ID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<int> QID { get; set; }
        public Nullable<bool> isDeleted { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual AcadmicProfessionalDetail AcadmicProfessionalDetail { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual tblMstEmployee tblMstEmployee { get; set; }
    }
}
