//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLGRATIADUMMY
    {
        public int SNO { get; set; }
        public string EMPCODE { get; set; }
        public string NAME { get; set; }
        public string Bankidno { get; set; }
        public string BANKNO { get; set; }
        public string RecordType { get; set; }
        public string HEAD { get; set; }
        public Nullable<decimal> APR { get; set; }
        public Nullable<decimal> MAY { get; set; }
        public Nullable<decimal> JUN { get; set; }
        public Nullable<decimal> JUL { get; set; }
        public Nullable<decimal> AUG { get; set; }
        public Nullable<decimal> SEP { get; set; }
        public Nullable<decimal> OCT { get; set; }
        public Nullable<decimal> NOV { get; set; }
        public Nullable<decimal> DECM { get; set; }
        public Nullable<decimal> JAN { get; set; }
        public Nullable<decimal> FEB { get; set; }
        public Nullable<decimal> MAR { get; set; }
        public Nullable<decimal> TOT1 { get; set; }
        public Nullable<decimal> grandtot { get; set; }
        public string BonusApr { get; set; }
        public string BonusMay { get; set; }
        public string BonusJune { get; set; }
        public string BonusJuly { get; set; }
        public string BonusAug { get; set; }
        public string BonusSep { get; set; }
        public string BonusOct { get; set; }
        public string BonusNov { get; set; }
        public string BonusDec { get; set; }
        public string BonusJan { get; set; }
        public string BonusFeb { get; set; }
        public string BonusMar { get; set; }
        public string Qualapr { get; set; }
        public string QualMay { get; set; }
        public string QualJune { get; set; }
        public string QualJuly { get; set; }
        public string QualAug { get; set; }
        public string QualSep { get; set; }
        public string QualOct { get; set; }
        public string QualNov { get; set; }
        public string QualDec { get; set; }
        public string QualJan { get; set; }
        public string QualFeb { get; set; }
        public string QualMar { get; set; }
        public string Year { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual tblMstEmployee tblMstEmployee { get; set; }
    }
}
