//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoanAdjustOld
    {
        public string PriorityNo { get; set; }
        public System.DateTime DateofDeposit { get; set; }
        public Nullable<int> ActualInstNoRem { get; set; }
        public Nullable<int> ChangedInstNoRem { get; set; }
        public Nullable<decimal> ActualInstAmt { get; set; }
        public Nullable<decimal> ChangedInstAmt { get; set; }
        public Nullable<decimal> ActualIntAmt { get; set; }
        public Nullable<decimal> ChangeIntAmt { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
