
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class tblMedicalLeaveUpdate
{

    public int medicalLeaveID { get; set; }

    public Nullable<int> Day { get; set; }

    public Nullable<int> Month { get; set; }

    public Nullable<int> Year { get; set; }

    public System.DateTime fulldate { get; set; }

    public Nullable<int> LeaveCategoryID { get; set; }

    public string LeaveType { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public int CreatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }



    public virtual LeaveCategory LeaveCategory { get; set; }

}

}
