//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMstLoanPriorityHistory
    {
        public Nullable<int> SerialNo { get; set; }
        public string Branchcode { get; set; }
        public string PriorityNo { get; set; }
        public string LoanType { get; set; }
        public string EmpCode { get; set; }
        public Nullable<System.DateTime> DateofApp { get; set; }
        public Nullable<System.DateTime> DateRcptApp { get; set; }
        public Nullable<decimal> ReqAmt { get; set; }
        public string Surety { get; set; }
        public Nullable<bool> LoanSanc { get; set; }
        public Nullable<System.DateTime> DateofSanc { get; set; }
        public Nullable<decimal> SancAmt { get; set; }
        public System.DateTime DateAvailLoan { get; set; }
        public Nullable<System.DateTime> EffDate { get; set; }
        public string Reasonref { get; set; }
        public Nullable<System.DateTime> Dateofref { get; set; }
        public Nullable<decimal> MaxLoanAmt { get; set; }
        public Nullable<decimal> ROI { get; set; }
        public Nullable<bool> Asubmitted { get; set; }
        public Nullable<bool> Bsubmitted { get; set; }
        public Nullable<bool> Csubmitted { get; set; }
        public Nullable<bool> Dsubmitted { get; set; }
        public Nullable<bool> Esubmitted { get; set; }
        public Nullable<bool> Fsubmitted { get; set; }
        public Nullable<bool> Gsubmitted { get; set; }
        public Nullable<bool> Hsubmitted { get; set; }
        public string Detail { get; set; }
        public string LoanMode { get; set; }
        public bool IsFloatingRate { get; set; }
        public bool IsInterestPayable { get; set; }
        public Nullable<int> OriginalPInstNo { get; set; }
        public Nullable<int> OriginalIInstNo { get; set; }
        public Nullable<decimal> OriginalPinstAmt { get; set; }
        public Nullable<decimal> InterestInstAmt { get; set; }
        public Nullable<decimal> BalancePAmt { get; set; }
        public Nullable<decimal> BalanceIAmt { get; set; }
        public Nullable<decimal> TotalBalanceAmt { get; set; }
        public Nullable<int> RemainingPInstNo { get; set; }
        public Nullable<int> RemainingIInstNo { get; set; }
        public string LastPaidInstDeduDt { get; set; }
        public Nullable<decimal> LastPaidPInstAmt { get; set; }
        public Nullable<decimal> LastPaidIInstAmt { get; set; }
        public Nullable<int> LastPaidPInstNo { get; set; }
        public Nullable<int> LastPaidIInstNo { get; set; }
        public Nullable<decimal> LastMonthInterest { get; set; }
        public Nullable<int> TotalSkippedInst { get; set; }
        public Nullable<decimal> CurrentROI { get; set; }
        public bool IsNewLoanAfterDevelop { get; set; }
        public bool Status { get; set; }
        public Nullable<decimal> LastInstAmt { get; set; }
        public Nullable<decimal> LastPAmt { get; set; }
        public Nullable<decimal> AdjustedSancAmt { get; set; }
        public Nullable<decimal> withdrawlAmt { get; set; }
        public Nullable<decimal> WithdrawlInterestAmt { get; set; }
        public Nullable<System.DateTime> Wdate { get; set; }
        public Nullable<byte> Rmonth { get; set; }
        public Nullable<short> Ryear { get; set; }
        public Nullable<decimal> PARTREFUND { get; set; }
        public Nullable<decimal> PARTREFUNDINT { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public int LoanTypeId { get; set; }
        public string period { get; set; }
        public int MstLoanID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> RefLoanMstID { get; set; }
    }
}
