//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPropertyReturnHDR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPropertyReturnHDR()
        {
            this.tblPropertyReturns = new HashSet<tblPropertyReturn>();
        }
    
        public int PRID { get; set; }
        public int Year { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public string StatusID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public System.DateTime Duedate { get; set; }
        public Nullable<bool> NotApplicable { get; set; }
        public Nullable<decimal> E_Basic { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Department Department { get; set; }
        public virtual tblMstEmployee tblMstEmployee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPropertyReturn> tblPropertyReturns { get; set; }
        public virtual User User { get; set; }
        public virtual tblPropertyReturnHDR tblPropertyReturnHDR1 { get; set; }
        public virtual tblPropertyReturnHDR tblPropertyReturnHDR2 { get; set; }
        public virtual User User1 { get; set; }
        public virtual Designation Designation { get; set; }
    }
}
