//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPFOpBalance
    {
        public string Employeecode { get; set; }
        public int PFAcNo { get; set; }
        public string Salmonth { get; set; }
        public int Salyear { get; set; }
        public string BRANCHCODE { get; set; }
        public Nullable<double> EmplOpBal { get; set; }
        public Nullable<double> EmplrOpBal { get; set; }
        public Nullable<decimal> EmployeePFCont { get; set; }
        public Nullable<decimal> VPF { get; set; }
        public Nullable<decimal> Pension { get; set; }
        public Nullable<decimal> EmployerPFCont { get; set; }
        public Nullable<decimal> EmployeeInterest { get; set; }
        public Nullable<decimal> EmployerInterest { get; set; }
        public Nullable<decimal> InterestNRPFLoan { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> NonRefundLoan { get; set; }
        public Nullable<decimal> TotalPFBalance { get; set; }
        public Nullable<decimal> InterestTotal { get; set; }
        public Nullable<double> TotalPFOpeningEmpl { get; set; }
        public Nullable<double> TotalPFOpeningEmplr { get; set; }
        public Nullable<decimal> WithdrawlEmployeeAc { get; set; }
        public Nullable<decimal> WithdrawlEmployerAc { get; set; }
        public Nullable<decimal> AdditionEmployeeAc { get; set; }
        public Nullable<decimal> AdditionEmployerAc { get; set; }
        public Nullable<decimal> IntWDempl { get; set; }
        public Nullable<decimal> IntWDemplr { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> PF_DAarear { get; set; }
        public Nullable<decimal> VPF_DAarear { get; set; }
        public Nullable<decimal> PF_payarear { get; set; }
        public Nullable<decimal> VPF_payarear { get; set; }
        public Nullable<bool> PensionDeduct { get; set; }
        public Nullable<bool> IsInterestCalculate { get; set; }
        public Nullable<decimal> additionEmpInt { get; set; }
        public Nullable<decimal> additionEmployerInt { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<double> EmplClBal { get; set; }
        public Nullable<double> EmplrClBal { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
