//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPFFlagStatu
    {
        public string EmployeeCode { get; set; }
        public decimal PFno { get; set; }
        public Nullable<bool> EDLIFlag { get; set; }
        public Nullable<bool> FPFFlag { get; set; }
        public Nullable<bool> ZeroFlag { get; set; }
        public Nullable<bool> Pensiondeduct { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<bool> Forcefully { get; set; }
        public Nullable<decimal> AmountOfWages { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public Nullable<System.DateTime> DATEENTITLEMENTPS { get; set; }
        public Nullable<System.DateTime> DOJ_3PS { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    }
}
