//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPFOPBalanceManual
    {
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string PFNo { get; set; }
        public Nullable<double> EPF { get; set; }
        public Nullable<double> VPF { get; set; }
        public Nullable<double> EmpPF { get; set; }
        public Nullable<double> Pension { get; set; }
        public Nullable<double> WithEmp { get; set; }
        public Nullable<double> WithEmplr { get; set; }
        public Nullable<double> AddEmp { get; set; }
        public Nullable<double> AddEmplr { get; set; }
        public Nullable<double> IntEmp { get; set; }
        public Nullable<double> IntEmplr { get; set; }
        public Nullable<decimal> additionEmpInt { get; set; }
        public Nullable<decimal> additionEmployerInt { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int id { get; set; }
    }
}
