//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStaffBudget
    {
        public string Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<short> BudgetedStaff { get; set; }
        public Nullable<short> PresentStaff { get; set; }
        public Nullable<short> Vac { get; set; }
        public Nullable<short> FLTC { get; set; }
        public Nullable<short> FPromotion { get; set; }
        public Nullable<short> FDirect { get; set; }
        public Nullable<short> VRS { get; set; }
        public Nullable<short> Upgrade { get; set; }
        public Nullable<short> Creation { get; set; }
        public Nullable<short> ForceFully { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public int StaffBudgetId { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Designation Designation { get; set; }
        public virtual Designation Designation1 { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
