//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTDSTaxRulesSlab
    {
        public string FinancialYear { get; set; }
        public Nullable<decimal> StandardDeduction { get; set; }
        public Nullable<decimal> NoTaxTillSal { get; set; }
        public Nullable<decimal> FirstSlabUpperLimit { get; set; }
        public Nullable<decimal> FirstSlabTaxPercentage { get; set; }
        public Nullable<decimal> FirstSlabTaxSurchage { get; set; }
        public Nullable<decimal> SecondSlabUpperLimit { get; set; }
        public Nullable<decimal> SecondSlabTaxPercentage { get; set; }
        public Nullable<decimal> SecondSlabTaxSurchage { get; set; }
        public Nullable<decimal> ThirdSlabUpperLimit { get; set; }
        public Nullable<decimal> ThirdSlabTaxPercentage { get; set; }
        public Nullable<decimal> ThirdSlabTaxSurchage { get; set; }
        public Nullable<decimal> FemaleNoTaxTillSal { get; set; }
        public Nullable<decimal> FemaleFirstSlabUpperLimit { get; set; }
        public Nullable<decimal> FemaleFirstSlabTaxPercentage { get; set; }
        public Nullable<decimal> FemaleFirstSlabTaxSurchage { get; set; }
        public Nullable<decimal> FemaleSecondSlabUpperLimit { get; set; }
        public Nullable<decimal> FemaleSecondSlabTaxPercentage { get; set; }
        public Nullable<decimal> FemaleSecondSlabTaxSurchage { get; set; }
        public Nullable<decimal> FemaleThirdSlabUpperLimit { get; set; }
        public Nullable<decimal> FemaleThirdSlabTaxPercentage { get; set; }
        public Nullable<decimal> FemaleThirdSlabTaxSurchage { get; set; }
        public Nullable<decimal> SnrctnNoTaxTillSal { get; set; }
        public Nullable<decimal> SnrctnFirstSlabUpperLimit { get; set; }
        public Nullable<decimal> SnrctnFirstSlabTaxPercentage { get; set; }
        public Nullable<decimal> SnrctnFirstSlabTaxSurcharge { get; set; }
        public Nullable<decimal> SnrctnSecondSlabUpperLimit { get; set; }
        public Nullable<decimal> SnrctnSecondSlabTaxPercentage { get; set; }
        public Nullable<decimal> SnrctnSecondSlabTaxSurcharge { get; set; }
        public Nullable<decimal> SnrctnAgeLimit { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
