//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nafed.MicroPay.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingFeedBackFormDtl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainingFeedBackFormDtl()
        {
            this.TrainingFeedbackDetails = new HashSet<TrainingFeedbackDetail>();
        }
    
        public int FeedBackFormDtlID { get; set; }
        public int FeedBackFormHdrID { get; set; }
        public string SectionPrefix { get; set; }
        public string Section { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<bool> DisplayInBold { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public Nullable<int> PartNo { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual TrainingFeedBackFormHdr TrainingFeedBackFormHdr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainingFeedbackDetail> TrainingFeedbackDetails { get; set; }
    }
}
