
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TrainingFeedbackFormat
{

    public int TFeedbackID { get; set; }

    public int PartNo { get; set; }

    public string Prefix { get; set; }

    public string Question { get; set; }

}

}
