
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TrainingFeedBackFormHdr
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public TrainingFeedBackFormHdr()
    {

        this.TrainingFeedBackFormDtls = new HashSet<TrainingFeedBackFormDtl>();

        this.TrainingFeedbackDetails = new HashSet<TrainingFeedbackDetail>();

    }


    public int FeedBackFormHdrID { get; set; }

    public int TrainingID { get; set; }

    public string RatingType { get; set; }

    public Nullable<byte> LowerRatingValue { get; set; }

    public Nullable<byte> UpperRatingValue { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public bool IsDeleted { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingFeedBackFormDtl> TrainingFeedBackFormDtls { get; set; }

    public virtual User User { get; set; }

    public virtual User User1 { get; set; }

    public virtual Training Training { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingFeedbackDetail> TrainingFeedbackDetails { get; set; }

}

}
