
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class UserLoginDetails
{

    public int Id { get; set; }

    public string UserName { get; set; }

    public Nullable<System.DateTime> LoginTime { get; set; }

    public Nullable<System.DateTime> LogOutTime { get; set; }

    public string Remarks { get; set; }

    public string SessionId { get; set; }



    public virtual UserLoginDetails UserLoginDetails1 { get; set; }

    public virtual UserLoginDetails UserLoginDetails2 { get; set; }

}

}
