
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nafed.MicroPay.Data.Models
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public User()
    {

        this.AcadmicProfessionalDetails = new HashSet<AcadmicProfessionalDetail>();

        this.AcadmicProfessionalDetails1 = new HashSet<AcadmicProfessionalDetail>();

        this.BloodGroups = new HashSet<BloodGroup>();

        this.BloodGroups1 = new HashSet<BloodGroup>();

        this.Branches = new HashSet<Branch>();

        this.Branches1 = new HashSet<Branch>();

        this.Cadres = new HashSet<Cadre>();

        this.Cadres1 = new HashSet<Cadre>();

        this.Categories = new HashSet<Category>();

        this.Categories1 = new HashSet<Category>();

        this.Cities = new HashSet<City>();

        this.Cities1 = new HashSet<City>();

        this.Departments = new HashSet<Department>();

        this.Departments1 = new HashSet<Department>();

        this.DepartmentRights = new HashSet<DepartmentRight>();

        this.DepartmentRights1 = new HashSet<DepartmentRight>();

        this.Divisions = new HashSet<Division>();

        this.Divisions1 = new HashSet<Division>();

        this.Docments = new HashSet<Docment>();

        this.Docments1 = new HashSet<Docment>();

        this.DocumentExtensions = new HashSet<DocumentExtension>();

        this.DocumentExtensions1 = new HashSet<DocumentExtension>();

        this.EmailConfigurations = new HashSet<EmailConfiguration>();

        this.EmailConfigurations1 = new HashSet<EmailConfiguration>();

        this.EmployeeCategories = new HashSet<EmployeeCategory>();

        this.EmployeeCategories1 = new HashSet<EmployeeCategory>();

        this.EmployeeTypes = new HashSet<EmployeeType>();

        this.EmployeeTypes1 = new HashSet<EmployeeType>();

        this.Genders = new HashSet<Gender>();

        this.Genders1 = new HashSet<Gender>();

        this.Grades = new HashSet<Grade>();

        this.Grades1 = new HashSet<Grade>();

        this.LeavePurposes = new HashSet<LeavePurpose>();

        this.LeavePurposes1 = new HashSet<LeavePurpose>();

        this.LeaveRules = new HashSet<LeaveRule>();

        this.LeaveRules1 = new HashSet<LeaveRule>();

        this.MaritalStatus = new HashSet<MaritalStatu>();

        this.MaritalStatus1 = new HashSet<MaritalStatu>();

        this.Menus = new HashSet<Menu>();

        this.Menus1 = new HashSet<Menu>();

        this.MotherTongues = new HashSet<MotherTongue>();

        this.MotherTongues1 = new HashSet<MotherTongue>();

        this.ProcessStages = new HashSet<ProcessStage>();

        this.ProcessStages1 = new HashSet<ProcessStage>();

        this.Relations = new HashSet<Relation>();

        this.Relations1 = new HashSet<Relation>();

        this.Religions = new HashSet<Religion>();

        this.Religions1 = new HashSet<Religion>();

        this.Sections = new HashSet<Section>();

        this.Sections1 = new HashSet<Section>();

        this.SMSConfigurations = new HashSet<SMSConfiguration>();

        this.SMSConfigurations1 = new HashSet<SMSConfiguration>();

        this.StaffGrievances = new HashSet<StaffGrievance>();

        this.StaffGrievances1 = new HashSet<StaffGrievance>();

        this.States = new HashSet<State>();

        this.States1 = new HashSet<State>();

        this.Titles = new HashSet<Title>();

        this.Titles1 = new HashSet<Title>();

        this.ArrearDetails = new HashSet<ArrearDetail>();

        this.ArrearDetails1 = new HashSet<ArrearDetail>();

        this.UserRights = new HashSet<UserRight>();

        this.AttendanceTypes = new HashSet<AttendanceType>();

        this.AttendanceTypes1 = new HashSet<AttendanceType>();

        this.Holidays = new HashSet<Holiday>();

        this.Holidays1 = new HashSet<Holiday>();

        this.LeaveStatus = new HashSet<LeaveStatu>();

        this.LeaveStatus1 = new HashSet<LeaveStatu>();

        this.tblLeaveBals = new HashSet<tblLeaveBal>();

        this.tblLeaveBals1 = new HashSet<tblLeaveBal>();

        this.tblCCAMasters = new HashSet<tblCCAMaster>();

        this.tblCCAMasters1 = new HashSet<tblCCAMaster>();

        this.TblHeadLookups = new HashSet<TblHeadLookup>();

        this.TblHeadLookups1 = new HashSet<TblHeadLookup>();

        this.tblMstBanks = new HashSet<tblMstBank>();

        this.tblMstBanks1 = new HashSet<tblMstBank>();

        this.tblMstDailyWageRates = new HashSet<tblMstDailyWageRate>();

        this.tblMstDailyWageRates1 = new HashSet<tblMstDailyWageRate>();

        this.tblmstFDAs = new HashSet<tblmstFDA>();

        this.tblmstFDAs1 = new HashSet<tblmstFDA>();

        this.tblOTARates = new HashSet<tblOTARate>();

        this.tblOTARates1 = new HashSet<tblOTARate>();

        this.tblWashingAllowances = new HashSet<tblWashingAllowance>();

        this.tblWashingAllowances1 = new HashSet<tblWashingAllowance>();

        this.SlabWiseHeadBreakups = new HashSet<SlabWiseHeadBreakup>();

        this.SlabWiseHeadBreakups1 = new HashSet<SlabWiseHeadBreakup>();

        this.SlabWiseHeadBreakups2 = new HashSet<SlabWiseHeadBreakup>();

        this.EmpAttendanceDetails = new HashSet<EmpAttendanceDetail>();

        this.EmpAttendanceDetails1 = new HashSet<EmpAttendanceDetail>();

        this.FormGroupActivities = new HashSet<FormGroupActivity>();

        this.FormGroupActivities1 = new HashSet<FormGroupActivity>();

        this.FormGroupADetail1 = new HashSet<FormGroupADetail1>();

        this.FormGroupADetail11 = new HashSet<FormGroupADetail1>();

        this.FormGroupADetail2 = new HashSet<FormGroupADetail2>();

        this.FormGroupADetail21 = new HashSet<FormGroupADetail2>();

        this.FormGroupCDetail1 = new HashSet<FormGroupCDetail1>();

        this.FormGroupCDetail11 = new HashSet<FormGroupCDetail1>();

        this.FormGroupCDetail2 = new HashSet<FormGroupCDetail2>();

        this.FormGroupCDetail21 = new HashSet<FormGroupCDetail2>();

        this.LeaveCreditRules = new HashSet<LeaveCreditRule>();

        this.LeaveCreditRules1 = new HashSet<LeaveCreditRule>();

        this.EmployeeLeaves = new HashSet<EmployeeLeave>();

        this.EmployeeLeaves1 = new HashSet<EmployeeLeave>();

        this.FormGroupTrainingDtls = new HashSet<FormGroupTrainingDtl>();

        this.FormGroupTrainingDtls1 = new HashSet<FormGroupTrainingDtl>();

        this.FormGroupEDetail1 = new HashSet<FormGroupEDetail1>();

        this.FormGroupEDetail11 = new HashSet<FormGroupEDetail1>();

        this.FormGroupEDetail2 = new HashSet<FormGroupEDetail2>();

        this.FormGroupEDetail21 = new HashSet<FormGroupEDetail2>();

        this.FormGroupFDetail1 = new HashSet<FormGroupFDetail1>();

        this.FormGroupFDetail11 = new HashSet<FormGroupFDetail1>();

        this.FormGroupFDetail2 = new HashSet<FormGroupFDetail2>();

        this.FormGroupFDetail21 = new HashSet<FormGroupFDetail2>();

        this.FormGroupBDetail1 = new HashSet<FormGroupBDetail1>();

        this.FormGroupBDetail11 = new HashSet<FormGroupBDetail1>();

        this.FormGroupBDetail2 = new HashSet<FormGroupBDetail2>();

        this.FormGroupBDetail21 = new HashSet<FormGroupBDetail2>();

        this.LeaveCategories = new HashSet<LeaveCategory>();

        this.LeaveCategories1 = new HashSet<LeaveCategory>();

        this.EmployeeDependents = new HashSet<EmployeeDependent>();

        this.EmployeeDependents1 = new HashSet<EmployeeDependent>();

        this.EmployeeProcessApprovals = new HashSet<EmployeeProcessApproval>();

        this.EmployeeProcessApprovals1 = new HashSet<EmployeeProcessApproval>();

        this.tblmsttransfers = new HashSet<tblmsttransfer>();

        this.tblmsttransfers1 = new HashSet<tblmsttransfer>();

        this.APARSkillSetDetails = new HashSet<APARSkillSetDetail>();

        this.APARSkillSetDetails1 = new HashSet<APARSkillSetDetail>();

        this.APARSkillSetFormHdrs = new HashSet<APARSkillSetFormHdr>();

        this.APARSkillSetFormHdrs1 = new HashSet<APARSkillSetFormHdr>();

        this.tblBranchManagerDetails = new HashSet<tblBranchManagerDetail>();

        this.tblBranchManagerDetails1 = new HashSet<tblBranchManagerDetail>();

        this.tblPropertyReturns = new HashSet<tblPropertyReturn>();

        this.tblPropertyReturns1 = new HashSet<tblPropertyReturn>();

        this.CandidateGovtWorkExperiences = new HashSet<CandidateGovtWorkExperience>();

        this.CandidateGovtWorkExperiences1 = new HashSet<CandidateGovtWorkExperience>();

        this.CandidateWorkExperiences = new HashSet<CandidateWorkExperience>();

        this.CandidateWorkExperiences1 = new HashSet<CandidateWorkExperience>();

        this.Requirements = new HashSet<Requirement>();

        this.Requirements1 = new HashSet<Requirement>();

        this.CandidateRegistrations = new HashSet<CandidateRegistration>();

        this.CandidateRegistrations1 = new HashSet<CandidateRegistration>();

        this.CandidateEducationSummaries = new HashSet<CandidateEducationSummary>();

        this.CandidateEducationSummaries1 = new HashSet<CandidateEducationSummary>();

        this.TrainingDocumentRepositories = new HashSet<TrainingDocumentRepository>();

        this.TrainingDocumentRepositories1 = new HashSet<TrainingDocumentRepository>();

        this.TrainingParticipants = new HashSet<TrainingParticipant>();

        this.TrainingParticipants1 = new HashSet<TrainingParticipant>();

        this.TrainingPrerequisites = new HashSet<TrainingPrerequisite>();

        this.TrainingPrerequisites1 = new HashSet<TrainingPrerequisite>();

        this.TrainingFeedBackFormDtls = new HashSet<TrainingFeedBackFormDtl>();

        this.TrainingFeedBackFormDtls1 = new HashSet<TrainingFeedBackFormDtl>();

        this.TrainingFeedBackFormHdrs = new HashSet<TrainingFeedBackFormHdr>();

        this.TrainingFeedBackFormHdrs1 = new HashSet<TrainingFeedBackFormHdr>();

        this.Trainings = new HashSet<Training>();

        this.Trainings1 = new HashSet<Training>();

        this.TrainingFeedbackDetails = new HashSet<TrainingFeedbackDetail>();

        this.TrainingFeedbackDetails1 = new HashSet<TrainingFeedbackDetail>();

        this.tblmstbankrates = new HashSet<tblmstbankrate>();

        this.tblmstbankrates1 = new HashSet<tblmstbankrate>();

        this.APARSkillSets = new HashSet<APARSkillSet>();

        this.APARSkillSets1 = new HashSet<APARSkillSet>();

        this.tblFinalMonthlySalaries = new HashSet<tblFinalMonthlySalary>();

        this.tblFinalMonthlySalaries1 = new HashSet<tblFinalMonthlySalary>();

        this.TBLMONTHLYINPUTs = new HashSet<TBLMONTHLYINPUT>();

        this.TBLMONTHLYINPUTs1 = new HashSet<TBLMONTHLYINPUT>();

        this.tblMstLoanTypes = new HashSet<tblMstLoanType>();

        this.tblMstLoanTypes1 = new HashSet<tblMstLoanType>();

        this.tblEmployeeQualificationdetails = new HashSet<tblEmployeeQualificationdetail>();

        this.tblEmployeeQualificationdetails1 = new HashSet<tblEmployeeQualificationdetail>();

        this.DashboardDocuments = new HashSet<DashboardDocument>();

        this.DashboardDocuments1 = new HashSet<DashboardDocument>();

        this.TblArrearMonthlyInputs = new HashSet<TblArrearMonthlyInput>();

        this.TblArrearMonthlyInputs1 = new HashSet<TblArrearMonthlyInput>();

        this.TblActualArrears = new HashSet<TblActualArrear>();

        this.TblActualArrears1 = new HashSet<TblActualArrear>();

        this.tblarrearmanualdatas = new HashSet<tblarrearmanualdata>();

        this.tblarrearmanualdatas1 = new HashSet<tblarrearmanualdata>();

        this.FileTrackingTypes = new HashSet<FileTrackingType>();

        this.FileTrackingTypes1 = new HashSet<FileTrackingType>();

        this.FileTrackingDocuments = new HashSet<FileTrackingDocument>();

        this.FileTrackingDocuments1 = new HashSet<FileTrackingDocument>();

        this.FileManagements = new HashSet<FileManagement>();

        this.FileManagements1 = new HashSet<FileManagement>();

        this.MonthlyTCSFiles = new HashSet<MonthlyTCSFile>();

        this.MonthlyTCSFiles1 = new HashSet<MonthlyTCSFile>();

        this.SalaryHeads = new HashSet<SalaryHead>();

        this.SalaryHeads1 = new HashSet<SalaryHead>();

        this.tblGisDeductions = new HashSet<tblGisDeduction>();

        this.tblGisDeductions1 = new HashSet<tblGisDeduction>();

        this.tblLoanTrans = new HashSet<tblLoanTran>();

        this.tblLoanTrans1 = new HashSet<tblLoanTran>();

        this.TblArrearDetails = new HashSet<TblArrearDetail>();

        this.TblArrearDetails1 = new HashSet<TblArrearDetail>();

        this.TblMstEmployeeSalaries = new HashSet<TblMstEmployeeSalary>();

        this.TblMstEmployeeSalaries1 = new HashSet<TblMstEmployeeSalary>();

        this.TBLGRATIADUMMies = new HashSet<TBLGRATIADUMMY>();

        this.TBLGRATIADUMMies1 = new HashSet<TBLGRATIADUMMY>();

        this.tblMstEmployees = new HashSet<tblMstEmployee>();

        this.tblMstEmployees1 = new HashSet<tblMstEmployee>();

        this.tblMstEmployees2 = new HashSet<tblMstEmployee>();

        this.tblMstEmployees3 = new HashSet<tblMstEmployee>();

        this.APARSkillSetFormDetails = new HashSet<APARSkillSetFormDetail>();

        this.APARSkillSetFormDetails1 = new HashSet<APARSkillSetFormDetail>();

        this.LoanApplications = new HashSet<LoanApplication>();

        this.LoanApplications1 = new HashSet<LoanApplication>();

        this.LoanApplicationHistories = new HashSet<LoanApplicationHistory>();

        this.LoanApplicationHistories1 = new HashSet<LoanApplicationHistory>();

        this.BonusMinimumMonthlyWages = new HashSet<BonusMinimumMonthlyWage>();

        this.BonusMinimumMonthlyWages1 = new HashSet<BonusMinimumMonthlyWage>();

        this.BonusMinimumMonthlyWages2 = new HashSet<BonusMinimumMonthlyWage>();

        this.BonusWages = new HashSet<BonusWage>();

        this.BonusWages1 = new HashSet<BonusWage>();

        this.TblBonusAmts = new HashSet<TblBonusAmt>();

        this.TblBonusAmts1 = new HashSet<TblBonusAmt>();

        this.TblExGratia_Cal = new HashSet<TblExGratia_Cal>();

        this.TblExGratia_Cal1 = new HashSet<TblExGratia_Cal>();

        this.tblmstslabs = new HashSet<tblmstslab>();

        this.tblmstslabs1 = new HashSet<tblmstslab>();

        this.OTASlips = new HashSet<OTASlip>();

        this.OTASlips1 = new HashSet<OTASlip>();

        this.EmployeeProvidentFundOrganisations = new HashSet<EmployeeProvidentFundOrganisation>();

        this.EmployeeProvidentFundOrganisations1 = new HashSet<EmployeeProvidentFundOrganisation>();

        this.BranchSalaryHeadRules = new HashSet<BranchSalaryHeadRule>();

        this.BranchSalaryHeadRules1 = new HashSet<BranchSalaryHeadRule>();

        this.tblMstLoanPriorities = new HashSet<tblMstLoanPriority>();

        this.tblMstLoanPriorities1 = new HashSet<tblMstLoanPriority>();

        this.PayrollApprovalRequests = new HashSet<PayrollApprovalRequest>();

        this.PayrollApprovalRequests1 = new HashSet<PayrollApprovalRequest>();

        this.tblPropertyReturnHDRs = new HashSet<tblPropertyReturnHDR>();

        this.tblPropertyReturnHDRs1 = new HashSet<tblPropertyReturnHDR>();

        this.EPFNominations = new HashSet<EPFNomination>();

        this.EPFNominations1 = new HashSet<EPFNomination>();

        this.EPFDetails = new HashSet<EPFDetail>();

        this.EPFDetails1 = new HashSet<EPFDetail>();

        this.ChildrenEducationDetails = new HashSet<ChildrenEducationDetail>();

        this.ChildrenEducationDetails1 = new HashSet<ChildrenEducationDetail>();

        this.ChildrenEducationDocuments = new HashSet<ChildrenEducationDocument>();

        this.ChildrenEducationDocuments1 = new HashSet<ChildrenEducationDocument>();

        this.ConveyanceBillDescriptions = new HashSet<ConveyanceBillDescription>();

        this.ConveyanceBillDescriptions1 = new HashSet<ConveyanceBillDescription>();

        this.ConveyanceBillHdrs = new HashSet<ConveyanceBillHdr>();

        this.ConveyanceBillHdrs1 = new HashSet<ConveyanceBillHdr>();

        this.Designations = new HashSet<Designation>();

        this.Designations1 = new HashSet<Designation>();

        this.tblStaffBudgets = new HashSet<tblStaffBudget>();

        this.tblStaffBudgets1 = new HashSet<tblStaffBudget>();

        this.NonRefundablePFLoans = new HashSet<NonRefundablePFLoan>();

        this.NonRefundablePFLoans1 = new HashSet<NonRefundablePFLoan>();

        this.EmpPFOrgHDRs = new HashSet<EmpPFOrgHDR>();

        this.EmpPFOrgHDRs1 = new HashSet<EmpPFOrgHDR>();

        this.EmpDeductionUnderChapterVI_A = new HashSet<EmpDeductionUnderChapterVI_A>();

        this.EmpDeductionUnderChapterVI_A1 = new HashSet<EmpDeductionUnderChapterVI_A>();

        this.EmployeeForm12BB = new HashSet<EmployeeForm12BB>();

        this.EmployeeForm12BB1 = new HashSet<EmployeeForm12BB>();

        this.EmployeeForm12BBDocument = new HashSet<EmployeeForm12BBDocument>();

        this.DeductionSections = new HashSet<DeductionSection>();

        this.DeductionSections1 = new HashSet<DeductionSection>();

        this.DeductionSubSections = new HashSet<DeductionSubSection>();

        this.DeductionSubSections1 = new HashSet<DeductionSubSection>();

        this.DeductionSubSections2 = new HashSet<DeductionSubSection>();

        this.DeductionSubSectionDescriptions = new HashSet<DeductionSubSectionDescription>();

        this.DeductionSubSectionDescriptions1 = new HashSet<DeductionSubSectionDescription>();

        this.DeductionSubSectionDescriptions2 = new HashSet<DeductionSubSectionDescription>();

        this.ChildrenEducationHdrs = new HashSet<ChildrenEducationHdr>();

        this.ChildrenEducationHdrs1 = new HashSet<ChildrenEducationHdr>();

        this.AssetTypes = new HashSet<AssetType>();

        this.AssetTypes1 = new HashSet<AssetType>();

        this.Manufacturers = new HashSet<Manufacturer>();

        this.Manufacturers1 = new HashSet<Manufacturer>();

        this.tblTDSTaxRulesSlabs = new HashSet<tblTDSTaxRulesSlab>();

        this.tblTDSTaxRulesSlabs1 = new HashSet<tblTDSTaxRulesSlab>();

        this.InventoryManagements = new HashSet<InventoryManagement>();

        this.InventoryManagements1 = new HashSet<InventoryManagement>();

        this.AssetmanagementDetails = new HashSet<AssetmanagementDetail>();

        this.AssetmanagementDetails1 = new HashSet<AssetmanagementDetail>();

        this.ConveyanceBillHdrDetails = new HashSet<ConveyanceBillHdrDetail>();

        this.NRPFLoanHDRs = new HashSet<NRPFLoanHDR>();

        this.NRPFLoanHDRs1 = new HashSet<NRPFLoanHDR>();

        this.Trainers = new HashSet<Trainer>();

        this.Trainers1 = new HashSet<Trainer>();

        this.ConfirmationClarifications = new HashSet<ConfirmationClarification>();

        this.ConfirmationClarifications1 = new HashSet<ConfirmationClarification>();

        this.ConfirmationFormAHeaders = new HashSet<ConfirmationFormAHeader>();

        this.ConfirmationFormAHeaders1 = new HashSet<ConfirmationFormAHeader>();

        this.ConfirmationFormBHeaders = new HashSet<ConfirmationFormBHeader>();

        this.ConfirmationFormBHeaders1 = new HashSet<ConfirmationFormBHeader>();

        this.EmployeeSuspensionPeriods = new HashSet<EmployeeSuspensionPeriod>();

        this.tblMstLTCs = new HashSet<tblMstLTC>();

        this.tblMstLTCs1 = new HashSet<tblMstLTC>();

        this.TicketWorkFlows = new HashSet<TicketWorkFlow>();

        this.TicketWorkFlows1 = new HashSet<TicketWorkFlow>();

        this.tickets = new HashSet<ticket>();

        this.tickets1 = new HashSet<ticket>();

        this.ticket_attachments = new HashSet<ticket_attachments>();

        this.ticket_attachments1 = new HashSet<ticket_attachments>();

        this.ConfirmationStatus = new HashSet<ConfirmationStatu>();

        this.ConfirmationStatus1 = new HashSet<ConfirmationStatu>();

        this.TrainingDateWiseTimeSlots = new HashSet<TrainingDateWiseTimeSlot>();

        this.PayrollApprovalSettings = new HashSet<PayrollApprovalSetting>();

        this.PayrollApprovalSettings1 = new HashSet<PayrollApprovalSetting>();

        this.ConfirmationFormHdrs = new HashSet<ConfirmationFormHdr>();

        this.ConfirmationFormHdrs1 = new HashSet<ConfirmationFormHdr>();

        this.ConfirmationFormHdrs2 = new HashSet<ConfirmationFormHdr>();

        this.FormGroupAHdrs = new HashSet<FormGroupAHdr>();

        this.FormGroupBHdrs = new HashSet<FormGroupBHdr>();

        this.FormGroupBHdrs1 = new HashSet<FormGroupBHdr>();

        this.FormGroupCHdrs = new HashSet<FormGroupCHdr>();

        this.FormGroupDHdrs = new HashSet<FormGroupDHdr>();

        this.FormGroupEHdrs = new HashSet<FormGroupEHdr>();

        this.AppraisalFormHdrs = new HashSet<AppraisalFormHdr>();

        this.DesignationAppraisalForms = new HashSet<DesignationAppraisalForm>();

        this.DesignationAppraisalForms1 = new HashSet<DesignationAppraisalForm>();

        this.APARReviewedSignedCopies = new HashSet<APARReviewedSignedCopy>();

        this.SubordinatesTrainings = new HashSet<SubordinatesTraining>();

        this.SubordinatesTrainings1 = new HashSet<SubordinatesTraining>();

        this.EmployeeAchievements = new HashSet<EmployeeAchievement>();

        this.EmployeeAchievements1 = new HashSet<EmployeeAchievement>();

        this.EmployeeCertifications = new HashSet<EmployeeCertification>();

        this.EmployeeCertifications1 = new HashSet<EmployeeCertification>();

        this.EmpAchievementAndCertificationDocuments = new HashSet<EmpAchievementAndCertificationDocument>();

        this.EmpAchievementAndCertificationDocuments1 = new HashSet<EmpAchievementAndCertificationDocument>();

        this.EmpAttendanceHdrs = new HashSet<EmpAttendanceHdr>();

        this.EmpAttendanceHdrs1 = new HashSet<EmpAttendanceHdr>();

        this.tblPFOpBalances = new HashSet<tblPFOpBalance>();

        this.tblPFOpBalances1 = new HashSet<tblPFOpBalance>();

        this.Insurances = new HashSet<Insurance>();

        this.Insurances1 = new HashSet<Insurance>();

        this.InsuranceDependents = new HashSet<InsuranceDependent>();

        this.InsuranceDependents1 = new HashSet<InsuranceDependent>();

        this.FTSUsers = new HashSet<FTSUser>();

        this.SeparationClearances = new HashSet<SeparationClearance>();

        this.SeparationClearances1 = new HashSet<SeparationClearance>();

        this.Seprations = new HashSet<Sepration>();

        this.Seprations1 = new HashSet<Sepration>();

        this.Resignations = new HashSet<Resignation>();

        this.Resignations1 = new HashSet<Resignation>();

        this.promotioncota1 = new HashSet<promotioncota1>();

        this.promotioncota11 = new HashSet<promotioncota1>();

        this.FileWorkflow = new HashSet<FileWorkflow>();

        this.NREmployeesContractExtention = new HashSet<NREmployeesContractExtention>();

        this.NREmployeesContractExtention1 = new HashSet<NREmployeesContractExtention>();

    }


    public int UserID { get; set; }

    public string UserName { get; set; }

    public string FullName { get; set; }

    public string Password { get; set; }

    public int DepartmentID { get; set; }

    public int UserTypeID { get; set; }

    public string MobileNo { get; set; }

    public string EmailID { get; set; }

    public int CreatedBy { get; set; }

    public System.DateTime CreatedOn { get; set; }

    public Nullable<int> UpdatedBy { get; set; }

    public Nullable<System.DateTime> UpdatedOn { get; set; }

    public bool IsActive { get; set; }

    public bool IsDeleted { get; set; }

    public string ImageName { get; set; }

    public Nullable<int> EmployeeID { get; set; }

    public Nullable<byte> WrongAttemp { get; set; }

    public Nullable<System.DateTime> LockDate { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AcadmicProfessionalDetail> AcadmicProfessionalDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AcadmicProfessionalDetail> AcadmicProfessionalDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BloodGroup> BloodGroups { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BloodGroup> BloodGroups1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Branch> Branches { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Branch> Branches1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cadre> Cadres { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Cadre> Cadres1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Category> Categories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Category> Categories1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<City> Cities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<City> Cities1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Department> Departments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Department> Departments1 { get; set; }

    public virtual Department Department { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DepartmentRight> DepartmentRights { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DepartmentRight> DepartmentRights1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Division> Divisions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Division> Divisions1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Docment> Docments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Docment> Docments1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DocumentExtension> DocumentExtensions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DocumentExtension> DocumentExtensions1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmailConfiguration> EmailConfigurations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmailConfiguration> EmailConfigurations1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeCategory> EmployeeCategories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeCategory> EmployeeCategories1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeType> EmployeeTypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeType> EmployeeTypes1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Gender> Genders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Gender> Genders1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Grade> Grades { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Grade> Grades1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeavePurpose> LeavePurposes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeavePurpose> LeavePurposes1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveRule> LeaveRules { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveRule> LeaveRules1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MaritalStatu> MaritalStatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MaritalStatu> MaritalStatus1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Menu> Menus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Menu> Menus1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MotherTongue> MotherTongues { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MotherTongue> MotherTongues1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProcessStage> ProcessStages { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ProcessStage> ProcessStages1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Relation> Relations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Relation> Relations1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Religion> Religions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Religion> Religions1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Section> Sections { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Section> Sections1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SMSConfiguration> SMSConfigurations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SMSConfiguration> SMSConfigurations1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StaffGrievance> StaffGrievances { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StaffGrievance> StaffGrievances1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<State> States { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<State> States1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Title> Titles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Title> Titles1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ArrearDetail> ArrearDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ArrearDetail> ArrearDetails1 { get; set; }

    public virtual User User1 { get; set; }

    public virtual User User2 { get; set; }

    public virtual UserType UserType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<UserRight> UserRights { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AttendanceType> AttendanceTypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AttendanceType> AttendanceTypes1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Holiday> Holidays { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Holiday> Holidays1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveStatu> LeaveStatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveStatu> LeaveStatus1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLeaveBal> tblLeaveBals { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLeaveBal> tblLeaveBals1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCCAMaster> tblCCAMasters { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblCCAMaster> tblCCAMasters1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblHeadLookup> TblHeadLookups { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblHeadLookup> TblHeadLookups1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstBank> tblMstBanks { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstBank> tblMstBanks1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstDailyWageRate> tblMstDailyWageRates { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstDailyWageRate> tblMstDailyWageRates1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblmstFDA> tblmstFDAs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblmstFDA> tblmstFDAs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblOTARate> tblOTARates { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblOTARate> tblOTARates1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblWashingAllowance> tblWashingAllowances { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblWashingAllowance> tblWashingAllowances1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SlabWiseHeadBreakup> SlabWiseHeadBreakups { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SlabWiseHeadBreakup> SlabWiseHeadBreakups1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SlabWiseHeadBreakup> SlabWiseHeadBreakups2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpAttendanceDetail> EmpAttendanceDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpAttendanceDetail> EmpAttendanceDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupActivity> FormGroupActivities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupActivity> FormGroupActivities1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupADetail1> FormGroupADetail1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupADetail1> FormGroupADetail11 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupADetail2> FormGroupADetail2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupADetail2> FormGroupADetail21 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupCDetail1> FormGroupCDetail1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupCDetail1> FormGroupCDetail11 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupCDetail2> FormGroupCDetail2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupCDetail2> FormGroupCDetail21 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveCreditRule> LeaveCreditRules { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveCreditRule> LeaveCreditRules1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeLeave> EmployeeLeaves { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeLeave> EmployeeLeaves1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupTrainingDtl> FormGroupTrainingDtls { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupTrainingDtl> FormGroupTrainingDtls1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupEDetail1> FormGroupEDetail1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupEDetail1> FormGroupEDetail11 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupEDetail2> FormGroupEDetail2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupEDetail2> FormGroupEDetail21 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupFDetail1> FormGroupFDetail1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupFDetail1> FormGroupFDetail11 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupFDetail2> FormGroupFDetail2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupFDetail2> FormGroupFDetail21 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupBDetail1> FormGroupBDetail1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupBDetail1> FormGroupBDetail11 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupBDetail2> FormGroupBDetail2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupBDetail2> FormGroupBDetail21 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveCategory> LeaveCategories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LeaveCategory> LeaveCategories1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeDependent> EmployeeDependents { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeDependent> EmployeeDependents1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeProcessApproval> EmployeeProcessApprovals { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeProcessApproval> EmployeeProcessApprovals1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblmsttransfer> tblmsttransfers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblmsttransfer> tblmsttransfers1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<APARSkillSetDetail> APARSkillSetDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<APARSkillSetDetail> APARSkillSetDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<APARSkillSetFormHdr> APARSkillSetFormHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<APARSkillSetFormHdr> APARSkillSetFormHdrs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBranchManagerDetail> tblBranchManagerDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblBranchManagerDetail> tblBranchManagerDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPropertyReturn> tblPropertyReturns { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPropertyReturn> tblPropertyReturns1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CandidateGovtWorkExperience> CandidateGovtWorkExperiences { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CandidateGovtWorkExperience> CandidateGovtWorkExperiences1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CandidateWorkExperience> CandidateWorkExperiences { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CandidateWorkExperience> CandidateWorkExperiences1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Requirement> Requirements { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Requirement> Requirements1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CandidateRegistration> CandidateRegistrations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CandidateRegistration> CandidateRegistrations1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CandidateEducationSummary> CandidateEducationSummaries { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CandidateEducationSummary> CandidateEducationSummaries1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingDocumentRepository> TrainingDocumentRepositories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingDocumentRepository> TrainingDocumentRepositories1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingParticipant> TrainingParticipants { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingParticipant> TrainingParticipants1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingPrerequisite> TrainingPrerequisites { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingPrerequisite> TrainingPrerequisites1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingFeedBackFormDtl> TrainingFeedBackFormDtls { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingFeedBackFormDtl> TrainingFeedBackFormDtls1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingFeedBackFormHdr> TrainingFeedBackFormHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingFeedBackFormHdr> TrainingFeedBackFormHdrs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Training> Trainings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Training> Trainings1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingFeedbackDetail> TrainingFeedbackDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingFeedbackDetail> TrainingFeedbackDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblmstbankrate> tblmstbankrates { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblmstbankrate> tblmstbankrates1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<APARSkillSet> APARSkillSets { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<APARSkillSet> APARSkillSets1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFinalMonthlySalary> tblFinalMonthlySalaries { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblFinalMonthlySalary> tblFinalMonthlySalaries1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TBLMONTHLYINPUT> TBLMONTHLYINPUTs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TBLMONTHLYINPUT> TBLMONTHLYINPUTs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstLoanType> tblMstLoanTypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstLoanType> tblMstLoanTypes1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmployeeQualificationdetail> tblEmployeeQualificationdetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblEmployeeQualificationdetail> tblEmployeeQualificationdetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DashboardDocument> DashboardDocuments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DashboardDocument> DashboardDocuments1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblArrearMonthlyInput> TblArrearMonthlyInputs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblArrearMonthlyInput> TblArrearMonthlyInputs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblActualArrear> TblActualArrears { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblActualArrear> TblActualArrears1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblarrearmanualdata> tblarrearmanualdatas { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblarrearmanualdata> tblarrearmanualdatas1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FileTrackingType> FileTrackingTypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FileTrackingType> FileTrackingTypes1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FileTrackingDocument> FileTrackingDocuments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FileTrackingDocument> FileTrackingDocuments1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FileManagement> FileManagements { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FileManagement> FileManagements1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MonthlyTCSFile> MonthlyTCSFiles { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<MonthlyTCSFile> MonthlyTCSFiles1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SalaryHead> SalaryHeads { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SalaryHead> SalaryHeads1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblGisDeduction> tblGisDeductions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblGisDeduction> tblGisDeductions1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLoanTran> tblLoanTrans { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblLoanTran> tblLoanTrans1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblArrearDetail> TblArrearDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblArrearDetail> TblArrearDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblMstEmployeeSalary> TblMstEmployeeSalaries { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblMstEmployeeSalary> TblMstEmployeeSalaries1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TBLGRATIADUMMY> TBLGRATIADUMMies { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TBLGRATIADUMMY> TBLGRATIADUMMies1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstEmployee> tblMstEmployees { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstEmployee> tblMstEmployees1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstEmployee> tblMstEmployees2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstEmployee> tblMstEmployees3 { get; set; }

    public virtual tblMstEmployee tblMstEmployee { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<APARSkillSetFormDetail> APARSkillSetFormDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<APARSkillSetFormDetail> APARSkillSetFormDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LoanApplication> LoanApplications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LoanApplication> LoanApplications1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LoanApplicationHistory> LoanApplicationHistories { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<LoanApplicationHistory> LoanApplicationHistories1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BonusMinimumMonthlyWage> BonusMinimumMonthlyWages { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BonusMinimumMonthlyWage> BonusMinimumMonthlyWages1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BonusMinimumMonthlyWage> BonusMinimumMonthlyWages2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BonusWage> BonusWages { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BonusWage> BonusWages1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblBonusAmt> TblBonusAmts { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblBonusAmt> TblBonusAmts1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblExGratia_Cal> TblExGratia_Cal { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TblExGratia_Cal> TblExGratia_Cal1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblmstslab> tblmstslabs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblmstslab> tblmstslabs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OTASlip> OTASlips { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<OTASlip> OTASlips1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeProvidentFundOrganisation> EmployeeProvidentFundOrganisations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeProvidentFundOrganisation> EmployeeProvidentFundOrganisations1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BranchSalaryHeadRule> BranchSalaryHeadRules { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<BranchSalaryHeadRule> BranchSalaryHeadRules1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstLoanPriority> tblMstLoanPriorities { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstLoanPriority> tblMstLoanPriorities1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PayrollApprovalRequest> PayrollApprovalRequests { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PayrollApprovalRequest> PayrollApprovalRequests1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPropertyReturnHDR> tblPropertyReturnHDRs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPropertyReturnHDR> tblPropertyReturnHDRs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EPFNomination> EPFNominations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EPFNomination> EPFNominations1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EPFDetail> EPFDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EPFDetail> EPFDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChildrenEducationDetail> ChildrenEducationDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChildrenEducationDetail> ChildrenEducationDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChildrenEducationDocument> ChildrenEducationDocuments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChildrenEducationDocument> ChildrenEducationDocuments1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConveyanceBillDescription> ConveyanceBillDescriptions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConveyanceBillDescription> ConveyanceBillDescriptions1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConveyanceBillHdr> ConveyanceBillHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConveyanceBillHdr> ConveyanceBillHdrs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Designation> Designations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Designation> Designations1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblStaffBudget> tblStaffBudgets { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblStaffBudget> tblStaffBudgets1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NonRefundablePFLoan> NonRefundablePFLoans { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NonRefundablePFLoan> NonRefundablePFLoans1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpPFOrgHDR> EmpPFOrgHDRs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpPFOrgHDR> EmpPFOrgHDRs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpDeductionUnderChapterVI_A> EmpDeductionUnderChapterVI_A { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpDeductionUnderChapterVI_A> EmpDeductionUnderChapterVI_A1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeForm12BB> EmployeeForm12BB { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeForm12BB> EmployeeForm12BB1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeForm12BBDocument> EmployeeForm12BBDocument { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeductionSection> DeductionSections { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeductionSection> DeductionSections1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeductionSubSection> DeductionSubSections { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeductionSubSection> DeductionSubSections1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeductionSubSection> DeductionSubSections2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeductionSubSectionDescription> DeductionSubSectionDescriptions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeductionSubSectionDescription> DeductionSubSectionDescriptions1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DeductionSubSectionDescription> DeductionSubSectionDescriptions2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChildrenEducationHdr> ChildrenEducationHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ChildrenEducationHdr> ChildrenEducationHdrs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AssetType> AssetTypes { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AssetType> AssetTypes1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Manufacturer> Manufacturers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Manufacturer> Manufacturers1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTDSTaxRulesSlab> tblTDSTaxRulesSlabs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblTDSTaxRulesSlab> tblTDSTaxRulesSlabs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InventoryManagement> InventoryManagements { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InventoryManagement> InventoryManagements1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AssetmanagementDetail> AssetmanagementDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AssetmanagementDetail> AssetmanagementDetails1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConveyanceBillHdrDetail> ConveyanceBillHdrDetails { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NRPFLoanHDR> NRPFLoanHDRs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NRPFLoanHDR> NRPFLoanHDRs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Trainer> Trainers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Trainer> Trainers1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfirmationClarification> ConfirmationClarifications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfirmationClarification> ConfirmationClarifications1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfirmationFormAHeader> ConfirmationFormAHeaders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfirmationFormAHeader> ConfirmationFormAHeaders1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfirmationFormBHeader> ConfirmationFormBHeaders { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfirmationFormBHeader> ConfirmationFormBHeaders1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeSuspensionPeriod> EmployeeSuspensionPeriods { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstLTC> tblMstLTCs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblMstLTC> tblMstLTCs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TicketWorkFlow> TicketWorkFlows { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TicketWorkFlow> TicketWorkFlows1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ticket> tickets { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ticket> tickets1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ticket_attachments> ticket_attachments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ticket_attachments> ticket_attachments1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfirmationStatu> ConfirmationStatus { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfirmationStatu> ConfirmationStatus1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<TrainingDateWiseTimeSlot> TrainingDateWiseTimeSlots { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PayrollApprovalSetting> PayrollApprovalSettings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<PayrollApprovalSetting> PayrollApprovalSettings1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfirmationFormHdr> ConfirmationFormHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfirmationFormHdr> ConfirmationFormHdrs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<ConfirmationFormHdr> ConfirmationFormHdrs2 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupAHdr> FormGroupAHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupBHdr> FormGroupBHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupBHdr> FormGroupBHdrs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupCHdr> FormGroupCHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupDHdr> FormGroupDHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FormGroupEHdr> FormGroupEHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AppraisalFormHdr> AppraisalFormHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DesignationAppraisalForm> DesignationAppraisalForms { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<DesignationAppraisalForm> DesignationAppraisalForms1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<APARReviewedSignedCopy> APARReviewedSignedCopies { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SubordinatesTraining> SubordinatesTrainings { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SubordinatesTraining> SubordinatesTrainings1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeAchievement> EmployeeAchievements { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeAchievement> EmployeeAchievements1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeCertification> EmployeeCertifications { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmployeeCertification> EmployeeCertifications1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpAchievementAndCertificationDocument> EmpAchievementAndCertificationDocuments { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpAchievementAndCertificationDocument> EmpAchievementAndCertificationDocuments1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpAttendanceHdr> EmpAttendanceHdrs { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<EmpAttendanceHdr> EmpAttendanceHdrs1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPFOpBalance> tblPFOpBalances { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tblPFOpBalance> tblPFOpBalances1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Insurance> Insurances { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Insurance> Insurances1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InsuranceDependent> InsuranceDependents { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InsuranceDependent> InsuranceDependents1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FTSUser> FTSUsers { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SeparationClearance> SeparationClearances { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<SeparationClearance> SeparationClearances1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sepration> Seprations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Sepration> Seprations1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Resignation> Resignations { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Resignation> Resignations1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<promotioncota1> promotioncota1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<promotioncota1> promotioncota11 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<FileWorkflow> FileWorkflow { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NREmployeesContractExtention> NREmployeesContractExtention { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<NREmployeesContractExtention> NREmployeesContractExtention1 { get; set; }

}

}
